addSbtPlugin("com.typesafe.sbt"          % "sbt-git"         % "1.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"    % "0.1.5")
addSbtPlugin("com.lucidchart"            % "sbt-scalafmt"    % "1.15")
addSbtPlugin("org.tpolecat"              % "tut-plugin"      % "0.6.10")
addSbtPlugin("com.47deg"                 % "sbt-microsites"  % "0.7.16")
addSbtPlugin("com.typesafe.sbt"          % "sbt-ghpages"     % "0.6.3")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"         % "0.3.4")
addSbtPlugin("com.typesafe"              % "sbt-mima-plugin" % "0.3.0")
